# Multivariate Statistical Methods: A Primer. 4th Edition
# Chapter 9. Cluster analysis
#
# Example 9.1: Clustering of European countries
#
# Hirerarchic cluster analysis, Nearest-neighbor
# Using library "cluster" (agnes function)
employ <- read.csv("Euroemp.csv",header=TRUE,row.names=1)
library(cluster)
attach(employ)
# Using command "agnes" in library cluster                                  
# This command allows to select data standardization, the distance measure and
# the clustering algorithm in one single function 
(agn.employ <- agnes(employ, metric="euclidean", stand=TRUE, method = "single"))
#  Description of cluster merging
agn.employ$merge
# The object generated by agnes is usable for dendrogram plotting
plot(as.dendrogram(agn.employ), xlab= "Distance between Countries",xlim=c(8,0),
     horiz = TRUE,main="Dendrogram \n Employment in nine industry groups in European countries")
# 
# Interactive plotting in agnes: banner and dendrogram (See "cluster" manual
# for details)
                                    
plot(agn.employ,ask=TRUE)                             
plot(agn.employ, which.plots=2)
# 
detach(employ)
#
# End of script
        