# Multivariate Statistical Methods: A Primer. 4th Edition
# Chapter 8. Discriminant function analysis
#
# Example 8.1: Comparison of samples of Egyptian skulls
# Canonical Discriminant Analysis using command "candisc", from "candisc" package
#
skulls <- read.csv("Egyptian skulls.csv",header=TRUE)
attach(skulls)
# Before running library(MASS) make sure you have installed the package
library(candisc)
# Candisc reads the object generated by lm (multivariate linear regression)
skulls.mod <- lm(cbind(Maximum.breadth, Basibregmatic.height,
                       Basialveolar.length, Nasal.height) ~ Period, data=skulls)
# Creating an object with the results of the canonical discriminant analysis
skulls.can <- candisc(skulls.mod, data=skulls)
# candisc generates its own scaling of eigenvectors   
summary(skulls.can)
# Plot of the first two canonical discriminant functions, showing the centroids                           
plot(skulls.can,xlim=c(-3,3))
#
detach(skulls)
#
# End of script                              



