# Multivariate Statistical Methods: A Primer. 4th Edition
# Chapter 8. Discriminant function analysis
#
# Example 8.2: Discriminating between groups of European countries
#
employ <- read.csv("Euroemp.csv",header=TRUE, row.names=1)
attach(employ)
# One-way MANOVA for the comparison of the four groups of countries
employ.mnv <- manova(as.matrix(employ[,-1])~ Group, data=employ)
summary.manova(employ.mnv,test="Wilks")
# Before running library(candisc) make sure you have installed the package
library(candisc)
# Candisc reads the object generated by lm (multivariate linear regression)
# Variable TC has been removed from the calculations, as explained in Example 8.2
employ.mod <- lm(cbind(AGR,MIN,MAN,PS,CON,SER,FIN,SPS)~Group,data=employ)
# Creating an object with the results of the canonical discriminant analysis
employ.can <- candisc(employ.mod, data=employ)
# candisc generates its own scaling of eigenvectors
summary(employ.can)
# A matrix containing the canonical structure coefficients on ndim dimensions, 
# i.e., the correlations between the original variates and the canonical scores.
# These are sometimes referred to as Total Structure Coefficients.                           
employ.can$structure
# The next command is equivalent to employ.can$structure but variable TC has 
# been added i.e. the correlations between the original percentages and the 
# three canonical variates are displayed (Table 8.5 with signs reversed)                        
cor(cbind(AGR,MIN,MAN,PS,CON,SER,FIN,SPS,TC),employ.can$scores[,2:4])
# Plot of European countries with their values for the first two canonical
# discriminant functions.      
plot(employ.can,xlim=c(-6,6))
points(employ.can$scores[,2],employ.can$scores[,3],col=Group)
text(employ.can$scores[,2],employ.can$scores[,3],labels=rownames(employ),cex=0.6,pos=3)
abline(v=0.8)
segments(0.8,-1.2,-6.5,-1.2)
text(5,4.6,"Eastern")
text(-5,4.6,"EU & EFTA")
text(-5.6,-5.6,"Other")
title("Plot of 30 European countries against their values \nfor the first two canonical discriminant functions")
# Allocation of countries to groups, using the discriminant function
# Before running library(MASS) make sure you have installed the package
library(MASS)
employ.lda <- lda(employ$Group ~ AGR+MIN+MAN+PS+CON+SER+FIN+SPS,data=employ)
# object class in function predict(lda.object) will produce a classification based on lda
Allocated.group <- predict(employ.lda)$class   
(table.alloc=cbind(data.frame(Group),Country,data.frame(Allocated.group)))      # Data frame
(skulls.table=table(Group,Allocated.group))                                     # Summary of allocations
# Plot of European countries with their scores on Axes 2 and 3
dev.new()
plot(employ.can, which=c(1,3),type="n",xlim=c(-6,6))
points(employ.can$scores[,2],employ.can$scores[,4],col=Group)
text(employ.can$scores[,2],employ.can$scores[,4],labels=rownames(employ),cex=0.6,pos=3)
abline(v=0.8)
text(4,5.6,"Eastern")
text(-3,5.6,"EU & EFTA")
title("Plot of 30 European countries against their values \n for the canonical discriminant functions 1 and 3")
#
detach(employ)
#
# End of script